In [1]:
import polars as pl
import pandas as pd
import preprocessing.transform_data as td

In [3]:
df_raw = pl.read_parquet("data/2022_data_ST4000DM000.parquet")

In [ ]:
col_list = td.feature_list(target=False)

In [ ]:
df_raw=df_raw

In [5]:
df_raw = td.filter_out_inconsistent_drives(df_raw)

In [6]:
Train, Test = td.custom_train_test_split(df_raw)

In [7]:
Train

['Z304KPVL',
 'Z305N3QG',
 'Z302ALD2',
 'Z3059JNX',
 'Z3058HTC',
 'S300Z65S',
 'Z305D6WT',
 'Z304LAJR',
 'Z304JJT8',
 'Z305GXPQ',
 'Z3058WSR',
 'Z304CK86',
 'S300XBPG',
 'Z305K2TW',
 'Z302CXFF',
 'Z3015CBH',
 'Z304HSC8',
 'Z304L8G2',
 'Z305DHAZ',
 'Z304HTY8',
 'Z3059JWS',
 'S3012EXQ',
 'Z305B763',
 'S301PSWQ',
 'Z303XYK9',
 'Z304L8RJ',
 'S300Z73N',
 'Z305DW34',
 'Z304KBRZ',
 'S301LMP6',
 'Z302B101',
 'Z305233G',
 'Z305DKM6',
 'Z305AMS3',
 'Z305KW3F',
 'Z305D56Z',
 'S301KQKM',
 'S30116WE',
 'S300Y26G',
 'S300YQT2',
 'Z305DVXT',
 'S301PSEX',
 'Z302B0WY',
 'Z304HKL2',
 'Z304JWH8',
 'Z304JJNY',
 'Z305DV25',
 'S301EDBH',
 'Z3059YKF',
 'S300XE23',
 'S301GQK1',
 'Z3057PQH',
 'Z304HRNZ',
 'S30114PN',
 'Z304JGAW',
 'Z3056M6D',
 'Z302TBMF',
 'Z305K1TZ',
 'S30113MA',
 'Z304KC5R',
 'S300TKPH',
 'Z304JJLG',
 'Z305D33V',
 'Z304KC3W',
 'Z305AJF7',
 'Z303D9L9',
 'Z305KSMW',
 'Z304LA6M',
 'S300Z6XN',
 'Z304L9TW',
 'Z30581ER',
 'Z305GX70',
 'S300ZQ9N',
 'Z303XYZ4',
 'S300Z71A',
 'Z304HN6S',
 'S300XJD0',
 'Z305Q0K6',
 'Z3028D6G',
 'S301GP12',
 'Z304L92A',
 'Z305D2PK',
 'Z305KNF8',
 'Z304L9BK',
 'Z304JVYS',
 'Z304JW79',
 'Z302SYW1',
 'Z305G3QW',
 'S3010LJ0',
 'Z304GGEQ',
 'Z304KBRV',
 'Z305AXAW',
 'Z303YQE7',
 'Z305GW0X',
 'Z305D5GL',
 'S300Z6GW',
 'Z304HQAX',
 'Z305D591',
 'S300Z413',
 'S300YPJT',
 'Z304R4S9',
 'Z305GXXX',
 'Z305B76T',
 'Z305GVE8',
 'Z305D6HC',
 'Z304KCYP',
 'Z304JA89',
 'Z302SWRC',
 'Z302AK33',
 'Z304KC8C',
 'Z302T812',
 'Z305APFM',
 'Z302F37E',
 'Z304K3TJ',
 'Z304L8Q5',
 'Z305DG0G',
 'Z304JG8M',
 'Z3029BET',
 'Z305D2ZP',
 'Z304KBZL',
 'S301PRFT',
 'S3011414',
 'Z304KR08',
 'Z305JT7Z',
 'S300Z0JR',
 'S300Z4GK',
 'Z3058BHN',
 'Z305GVWA',
 'Z305GV9K',
 'S3010A33',
 'Z3051Z5A',
 'Z304JHC4',
 'Z305M19F',
 'Z305GX5K',
 'Z302B1SA',
 'Z305D24F',
 'Z305DHAS',
 'S300WD9E',
 'Z305K280',
 'Z304YR8L',
 'Z302SXR8',
 'Z302BV9A',
 'S300ZRAF',
 'Z305GXXY',
 'Z302AKAK',
 'Z3026P67',
 'S301JM5E',
 'Z305HRY5',
 'Z304TJZY',
 'S300XBGA',
 'Z304VBWQ',
 'S300Z6MB',
 'Z304L9M0',
 'S30116TW',
 'Z304KBTC',
 'S300Z0H8',
 'Z304JW6F',
 'S300ZN40',
 'Z3058VPK',
 'Z305B9XG',
 'Z3027H4N',
 'Z3051LX0',
 'Z304JQ5V',
 'Z304HKF5',
 'S301GRV9',
 'Z304JHHH',
 'Z305963N',
 'Z304JW8K',
 'Z3059XP8',
 'S300Z7T8',
 'Z304RNFS',
 'S3010LXX',
 'Z304HEHV',
 'Z304KBXG',
 'S300XDW5',
 'S300YTB2',
 'Z302BQS5',
 'S301J2Z1',
 'Z304L9VT',
 'Z305Q0PD',
 'Z304L8Z1',
 'S300Z3ZE',
 'Z304W5R5',
 'Z305MBGN',
 'Z305EYPR',
 'S300Z6DC',
 'Z302SXMH',
 'S300Z52Q',
 'Z305B6WV',
 'S301NXPM',
 'Z300E1P8',
 'Z303DGBS',
 'S301PX2P',
 'Z304JWBA',
 'Z3059PF6',
 'Z302T6N0',
 'Z305GWWH',
 'Z305HJ5Y',
 'Z304JVYX',
 'Z304JFSS',
 'Z305956A',
 'S300VLAZ',
 'Z302T750',
 'Z304JW37',
 'Z305GX77',
 'Z304HSHD',
 'S300Z5D8',
 'Z305B6JZ',
 'S300Z6YS',
 'Z305GWLD',
 'Z302AL4V',
 'Z305N3P9',
 'S301LXB0',
 'Z304KBW3',
 'Z303ECH0',
 'S30114F3',
 'Z30583R7',
 'Z304XY3Y',
 'Z304RAWM',
 'Z304HV28',
 'Z305BT2T',
 'S300YSFW',
 'Z305B771',
 'Z305D2XA',
 'Z304SYQ5',
 'Z304HVWT',
 'Z302SZ97',
 'S301GNZJ',
 'S300WF0D',
 'Z304HV8H',
 'Z304JG81',
 'S301GV68',
 'S300Z7E4',
 'Z305PDSH',
 'S300VLBG',
 'Z302FZG5',
 'S301PSQJ',
 'Z302T6N7',
 'Z305GC1C',
 'Z302BTBG',
 'Z3058VWA',
 'Z305KFLW',
 'Z304LA9K',
 'S300Z6CS',
 'S300Z76B',
 'Z302A1AP',
 'Z302EPCH',
 'Z3058R6H',
 'Z305D59L',
 'Z303YNNX',
 'Z3052ZMQ',
 'Z304KCBF',
 'Z302AYKZ',
 'W300R8C4',
 'S301NHDQ',
 'S300Z747',
 'Z305GY02',
 'Z305D6VS',
 'Z304KA5Y',
 'Z305GV9C',
 'S300YH04',
 'Z302SY55',
 'Z305GXT3',
 'Z304SCJF',
 'S300Z7N2',
 'Z305GX6A',
 'Z305GVR2',
 'Z3056X73',
 'Z304JGC1',
 'S300Z5KP',
 'Z304JJ4E',
 'S300Z445',
 'Z304CK40',
 'S301KJ5R',
 'Z305K27N',
 'Z304JW5F',
 'Z304JWD8',
 'S300Z4YB',
 'S3011354',
 'Z3058VV0',
 'S300Z7G6',
 'Z304J0KG',
 'S300Z7F5',
 'S300XSN7',
 'Z305B72P',
 'Z302SYLH',
 'Z305L6DK',
 'Z305D6JQ',
 'Z302F3CD',
 'S3011636',
 'Z302T8MR',
 'S300YPJE',
 'S301GQ95',
 'Z305DVT7',
 'Z304LA9A',
 'S300Z6AR',
 'Z305B9NJ',
 'S301GPF2',
 'Z305AR7Q',
 'Z305KAPM',
 'Z305KWFW',
 'S300Z5RV',
 'Z304HK8X',
 'S300XB7Y',
 'Z3058ZEE',
 'Z304JZKM',
 'S300XCF3',
 'S300Z3T5',
 'S300Z490',
 'S301PRH4',
 'Z304HTQR',
 'Z305ARYZ',
 'Z3058CRQ',
 'S30117QC',
 'Z304HNXL',
 'Z304QP8G',
 'Z302SY7A',
 'Z305APAN',
 'Z302BQC4',
 'S300Z60M',
 'S301GPWR',
 'Z304JWA5',
 'W300R7PJ',
 'Z304JWMK',
 'Z305GK0D',
 'Z305FSD8',
 'Z304L955',
 'Z3056BHV',
 'Z30535J9',
 'Z302FD33',
 'S300YBTF',
 'Z305AR4F',
 'Z30292DX',
 'Z305750L',
 'Z304KCS6',
 'Z304RKFV',
 'Z302SWBX',
 'S301L0HB',
 'Z3026Z37',
 'S300YPKZ',
 'S301164M',
 'S300Z7CW',
 'S300Z5Z8',
 'Z305P015',
 'S300Z6M8',
 'Z304JFYG',
 'Z305D57H',
 'Z305AR4Z',
 'S300YBVN',
 'Z304HZJW',
 'S300Z46N',
 'Z305PH0P',
 'Z302B0BW',
 'Z304KBZR',
 'Z304XCDH',
 'Z302AKLE',
 'Z30544RK',
 'S301KE5C',
 'S301NPB4',
 'Z305D4JC',
 'Z3059L7G',
 'S30107BV',
 'Z304JGAE',
 'S300Z5KY',
 'Z305JFY5',
 'S3010M1Z',
 'Z304HT93',
 'Z305D2T2',
 'Z304L8B6',
 'S300X0XG',
 'Z305DHAJ',
 'S300WCLX',
 'Z304L8F4',
 'S301088Q',
 'Z304LADA',
 'Z302T6AX',
 'Z304JRP1',
 'S300Z8H0',
 'Z305GW5G',
 'S30116FF',
 'W300SSHW',
 'S300XC50',
 'Z300WQ39',
 'S300YT8B',
 'Z302SWPV',
 'Z3041PCZ',
 'S300YPMN',
 'Z304JFSZ',
 'Z303XYZE',
 'S300Z6K5',
 'Z3059PEW',
 'S301GMSE',
 'Z305B74M',
 'S300WD3R',
 'S300ZQAN',
 'Z302SVH6',
 'Z302SVG6',
 'Z3059JY1',
 'Z302SZGJ',
 'Z305B6HS',
 'Z305BB39',
 'Z302T8KS',
 'S300Z0Y8',
 'Z3057DGY',
 'S300Z818',
 'Z304JWHH',
 'Z3059BS3',
 'S300WEZG',
 'S300YTAC',
 'Z305K25K',
 'Z305Q0GL',
 'S3010MA5',
 'Z304JZFP',
 'Z3050P7X',
 'Z305BE3Q',
 'Z3053DN5',
 'Z304LA8W',
 'Z304KR2Z',
 'Z304KBZQ',
 'S300Z0PQ',
 'Z304HTA9',
 'Z304LADD',
 'Z3026RJJ',
 'S300Z6M1',
 'Z305K1Z8',
 'Z3042VED',
 'Z305FT0R',
 'Z305D59G',
 'Z302FR12',
 'Z305AKHW',
 'Z305D6HP',
 'Z304CTYF',
 'Z305DTP7',
 'S300Z709',
 'S301N73T',
 'Z305N36K',
 'Z304JG9B',
 'Z3056BV4',
 'Z305M8WY',
 'Z305D2GF',
 'Z305D51X',
 'Z302BYH7',
 'Z3058W51',
 'Z305G063',
 'Z305L2ZV',
 'W300SSEB',
 'Z305B740',
 'Z304KR0S',
 'Z304JGAD',
 'S300Z68A',
 'S300Z43V',
 'S300Z4PA',
 'Z302EVRG',
 'Z305B6P7',
 'Z305DV9W',
 'S301M82T',
 'Z305GX1L',
 'S300WDH2',
 'Z3059N9C',
 'Z304HZKK',
 'Z304JPTE',
 'Z304L8V6',
 'Z304JKBF',
 'S301GP51',
 'Z302DKKC',
 'Z302T6CS',
 'Z305D2L4',
 'S301PTCY',
 'Z305DHSY',
 'S3010V5B',
 'S300Z7NG',
 'Z304HT2Z',
 'Z304HSX6',
 'S300YPZA',
 'S301GMJR',
 'Z304V9FD',
 'S300ZMN1',
 'Z304HTWA',
 'Z305GXHC',
 'S300ZABY',
 'Z3015EHZ',
 'Z301D5FF',
 'S300Z5PA',
 'Z304JAP5',
 'Z302SY6A',
 'S300WE9T',
 'S300Z6SA',
 'Z305BF4X',
 'Z304JG0L',
 'S300Z4ER',
 'S300YPTB',
 'Z304K6DY',
 'Z305D6RK',
 'Z305GX8S',
 'Z304JW47',
 'S300Z72J',
 'Z304J2BX',
 'S301GMVB',
 'Z305K26V',
 'Z304JA2D',
 'Z305KX33',
 'Z304LKK5',
 'Z30574LW',
 'Z305D4MM',
 'Z302SYAF',
 'Z304LAG2',
 'S300VL6Z',
 'S300XRMP',
 'Z305GW4E',
 'Z302B0R6',
 'Z304JG64',
 'S300XAKC',
 'S301N6QY',
 'Z305KVMP',
 'Z305B75G',
 'S300Z787',
 'Z304KR0F',
 'Z304JNZP',
 'Z3056MS8',
 'Z305D5W4',
 'Z303XYNE',
 'Z302F1BX',
 'Z304L9XD',
 'S30109T7',
 'Z304DS52',
 'S300Z0X0',
 'Z302EQN3',
 'Z304JW0Z',
 'Z302AKA9',
 'Z305B6FS',
 'Z304HWN3',
 'S30117VQ',
 'Z304JNNJ',
 'Z304JGCP',
 'Z303XY93',
 'Z304VJRM',
 'S300Z679',
 'Z305D672',
 'S300Z6A9',
 'S3010AN1',
 'Z302AKCH',
 'Z305D509',
 'Z305D2R1',
 'Z304T95S',
 'S301NH04',
 'Z301CWYG',
 'Z305NZTA',
 'Z304KCYQ',
 'S30117YT',
 'Z3051N2B',
 'Z304GR3X',
 'Z305PDJ2',
 'Z302BSZD',
 'S301GQ1P',
 'S301NKT1',
 'Z305GWX5',
 'S300Z51K',
 'Z304JL8P',
 'Z304HSJB',
 'Z307BGTA',
 'Z302SZDB',
 'Z304KBRF',
 'S300Z06V',
 'Z302FS3B',
 'Z304L8SG',
 'S301GNER',
 'Z305D2ZL',
 'Z304L9QA',
 'Z305DEQF',
 'S300Z4EN',
 'Z305D5KR',
 'Z305PH38',
 'Z305NZLV',
 'S30108LB',
 'S300VKYD',
 'Z305D4YB',
 'Z304ELFQ',
 'Z304KCDW',
 'Z304JA9M',
 'Z302B8P6',
 'Z304JXBG',
 'Z304JMZZ',
 'Z301HR3B',
 'Z305KVYF',
 'Z304HVBK',
 'Z305D2NM',
 'Z305D6PF',
 'Z304HSTR',
 'Z304JWHK',
 'Z304L9BT',
 'S300YS9X',
 'Z305M04E',
 'Z305EGZT',
 'Z3059TCX',
 'Z304M8FZ',
 'Z305PTF5',
 'Z302AK7J',
 'S301GM8E',
 'S300Z7R7',
 'Z305AR6Y',
 'Z305CTN1',
 'Z305D4EZ',
 'Z305DY6S',
 'Z304HST8',
 'Z305D5BB',
 'Z304JAK7',
 'Z302ALC3',
 'S301LMM4',
 'Z305PW0Y',
 'Z304JW1W',
 'Z305BL6S',
 'Z302SW26',
 'Z302A1ZJ',
 'Z305D5K1',
 'Z3055LX1',
 'S301LMPQ',
 'Z305G7FE',
 'Z304L9EP',
 'Z305EJVN',
 'Z303QQD0',
 'Z305GWFY',
 'W3019A1D',
 'Z304HK92',
 'Z304KCS5',
 'Z304LAA8',
 'Z305KVJ6',
 'Z304JWP1',
 'S3010M3D',
 'S30107JD',
 'S301LME2',
 'Z304L8T8',
 'Z304JW59',
 'S301GMAQ',
 'S301K4BF',
 'S3010AH4',
 'S300XE9J',
 'S301PS8K',
 'Z302T6TW',
 'S301GM3H',
 'Z305AKK7',
 'Z304Q24V',
 'Z3029B57',
 'Z304KR35',
 'Z305ARDH',
 'Z3029AG2',
 'S3010M2K',
 'Z3029Z56',
 'Z302F0GB',
 'Z305GX94',
 'Z305D4QX',
 'S300Z64S',
 'S300Z0FV',
 'Z302SY0M',
 'S300YQ4G',
 'S300Z7KH',
 'S3010M7R',
 'Z304KCG2',
 'S300WCQ6',
 'Z305B737',
 'S300Z7MG',
 'Z305B6K2',
 'S300YPMP',
 'S3010M2A',
 'S30117DQ',
 'Z305KXV0',
 'Z305D6MS',
 'S300Z49W',
 'Z304JWA8',
 'Z304LAHV',
 'Z304JVYB',
 'Z305D4P5',
 'Z305D5G4',
 'Z305E8LA',
 'Z305GWA7',
 'Z302FZHC',
 'Z304JCXL',
 'Z3051B0E',
 'Z305KVL1',
 'Z302AJYL',
 'Z302SZDL',
 'Z304KCMX',
 'Z305AQH8',
 'Z305D6RM',
 'Z3050AS4',
 'Z304L9RS',
 'Z3050FKM',
 'Z305D2KJ',
 'Z304KDAT',
 'Z305D56X',
 'Z305D6B1',
 'S300WEZY',
 'Z305DW2A',
 'Z305D2M2',
 'Z304KC6W',
 'Z304SJN2',
 'Z3040E1H',
 'Z302AKA3',
 'Z305K02G',
 'Z304JG03',
 'Z302SY6W',
 'Z3051QF3',
 'Z305B70B',
 'Z3029F1D',
 'Z305DTXA',
 'Z3029ZW3',
 'S300Z415',
 'S300Z4EV',
 'S3010LGD',
 'Z305D546',
 'Z304VK34',
 'Z304HSA7',
 'Z307X70A',
 'S301154R',
 'Z304JAPB',
 'Z304L8T9',
 'S3010MAC',
 'S301NGGN',
 'Z304L94J',
 'Z305Q04X',
 'Z305D6GT',
 'Z305JN03',
 'Z3041MNT',
 'Z304JGCS',
 'Z305KWT8',
 'Z305K1Y3',
 'Z300XG3F',
 'S300YCVQ',
 'Z305GVPL',
 'S300VKMK',
 'Z304HZ67',
 'S300Z4RR',
 'Z305N37Y',
 'Z302B0BC',
 'Z304LEFV',
 'Z304NDC3',
 'S300Z7LA',
 'Z305GBX5',
 'Z302T6LM',
 'Z302F1MH',
 'S301106R',
 'Z304LAC9',
 'S300VL06',
 'Z305DTZM',
 'Z303LKKB',
 'Z3050XW9',
 'Z3039HST',
 'Z304J0MJ',
 'Z305D5C8',
 'S300Z69J',
 'S301GNWP',
 'Z305AP6C',
 'S300Z830',
 'Z305L18A',
 'Z304W9V7',
 'Z302AYQ7',
 'Z302AJXB',
 'Z304L8TZ',
 'S300Z62Z',
 'S300ZP2H',
 'Z305GX0T',
 'Z305GWX2',
 'Z305FZJ0',
 'Z304JXXZ',
 'Z304KEWJ',
 'Z305D3EG',
 'Z304KC50',
 'Z304JWFH',
 'Z304JY8D',
 'S300XE1B',
 'Z302AHEP',
 'Z305F9Z2',
 'S301NDB6',
 'S300YH0F',
 'Z304L8YL',
 'Z305GXTW',
 'Z304K3RK',
 'Z301YY6G',
 'S300XLK8',
 'S301KWTZ',
 'Z304KBN3',
 'Z305PVVA',
 'Z302SWCG',
 'W300SS9S',
 'Z3058WKQ',
 'S300YSNC',
 'S300Z94Y',
 'Z304JLCT',
 'Z304JFZK',
 'S300Z6X0',
 'S300Z0WZ',
 'Z3056A8W',
 'Z3029YT4',
 'Z3057B5N',
 'S3010LMR',
 'S3010LK7',
 'Z305DVN8',
 'Z3029G79',
 'S301GMLG',
 'Z304JXWM',
 'Z304JQ3G',
 'S300YCZS',
 'Z305K1XD',
 'Z304JNGX',
 'Z304J1PC',
 'Z305GW2A',
 'Z304YSMB',
 'S3011719',
 'Z3059KH6',
 'W300R9GF',
 'Z305PTFF',
 'Z302SXMQ',
 'Z302SXA0',
 'Z305K0VN',
 'Z304HLJN',
 'Z304HSY1',
 'Z304HK9F',
 'Z305GXL2',
 'Z305D2WC',
 'Z304KCF8',
 'Z302AKKM',
 'Z304HT8M',
 'Z304JFAM',
 'Z305D6X8',
 'Z305M0M2',
 'Z305D6NP',
 'S300Z5SX',
 'Z304HS9Y',
 'Z304HTFM',
 'S301GNG1',
 'Z302RBRZ',
 'W300R8K4',
 'Z302SWKA',
 'Z304KC1B',
 'S300YQBE',
 'Z304KCB2',
 'Z305AKF6',
 'S300YQY9',
 'Z303PDM5',
 'Z305B70X',
 'Z302B0B7',
 'Z305D2SR',
 'Z304JYKV',
 'Z305APWE',
 'Z305DHRE',
 'Z30428D4',
 'Z305FJJL',
 'Z303XYEF',
 'W300R8HJ',
 'Z304JWJT',
 'Z305KXEC',
 'Z304HLZ8',
 'Z305DVXC',
 'Z305B2RL',
 'Z3053JWR',
 'S30111FZ',
 'Z304JWN5',
 'Z304HKGN',
 'Z303LXKG',
 'Z305F9HL',
 'Z305ATC4',
 'Z304JAFQ',
 'Z304HKCA',
 'Z3029ASR',
 'Z3052KZ8',
 'S301NKK2',
 'S301GQA2',
 'Z304KBR3',
 'Z305N2W2',
 'Z305K1VC',
 'Z3041D6B',
 'S3010AQ5',
 'S300Z7RL',
 'Z3059JQY',
 'Z300CRJW',
 'S301GQRF',
 'Z305FQ63',
 'S300VL6E',
 'S300YQMD',
 'Z304KCWB',
 'Z304L8NG',
 'Z304L9ZP',
 'Z305KVHM',
 'Z305DVX1',
 'Z3029AJE',
 'Z304Y9TK',
 'Z305AQL6',
 'Z305DGMT',
 'Z3058B47',
 'Z30576NJ',
 'Z304KR2K',
 'Z305K20L',
 'S3011618',
 'Z302G04R',
 'Z305KBJR',
 'Z304JGN5',
 'Z302AK14',
 'S301GTLV',
 'S300Z4KR',
 'Z3051ZC8',
 'Z304Q77G',
 'Z302AK0N',
 'Z304JG1Y',
 'S300YBS5',
 'Z305DHVE',
 'Z304JW7Z',
 'S3010LWY',
 'Z307STPA',
 'Z305GL6M',
 'Z305GXMZ',
 'Z305DD8S',
 'S30108MP',
 'Z3029ZLK',
 'Z304Y4B5',
 'Z305D6PD',
 'Z305K1ZW',
 'S300Z4XS',
 'S301LPGH',
 'Z304JZML',
 'Z304KC70',
 'S300X9R4',
 'Z305GXL6',
 'Z304KBWF',
 'Z304GR60',
 'Z305AQVF',
 'Z305GV7X',
 'Z305GXHA',
 'Z305AT4C',
 'Z302SZA0',
 'Z304HNVC',
 'S300Z5V0',
 'S301M892',
 'Z304JWNC',
 'Z305D6H4',
 'Z304L8SD',
 'Z305PDXR',
 'S300Z6E3',
 'Z304Z6ZM',
 'Z305DHRZ',
 'Z304HNFW',
 'Z3051FMB',
 'Z305D8R4',
 'S301DKWJ',
 'S3016LT5',
 'Z304XZKM',
 'S301KJJN',
 'Z305B5TG',
 'S301L3AP',
 'Z302ETW7',
 'Z302AB5S',
 'Z304JVYH',
 'S301PS6L',
 'Z304L93J',
 'S300XD4W',
 'Z305APKB',
 'Z304J293',
 'Z302A13M',
 'Z305BYC2',
 'Z304KC5N',
 'S301F89W',
 'Z305GWY3',
 'S3010M82',
 'S300Z60H',
 'Z305BCFG',
 'S300XPY8',
 'Z303R58Z',
 'Z3029B2T',
 'Z305B6Z5',
 'Z305NCHW',
 'S301170W',
 'Z304LA9Q',
 'Z305PHZZ',
 'Z304KBKH',
 'Z304HSD7',
 'S300YPV0',
 'Z303RK8B',
 'S301NXWC',
 'Z3058W9A',
 'Z302SWS3',
 'Z305GXEJ',
 'Z305BT4Y',
 'S300WF0X',
 'Z305FZWX',
 'Z304L96E',
 'Z304Z4W1',
 'Z305D4BE',
 'Z305092N',
 'Z303RFZ4',
 'Z305D2L1',
 'Z302SY6C',
 'Z3053318',
 'Z302SY4C',
 'Z304JGDJ',
 'S300Z6VY',
 'Z3029GBF',
 'Z305PDPV',
 'S300Z7RV',
 'Z304EL1R',
 'Z305D6JS',
 'Z304JFB5',
 'Z305KTQ9',
 ...]

In [8]:
serial_nr_train = td.get_serial(df_raw)

In [13]:
# Yield successive n-sized
# chunks from l.
#def divide_chunks(l, n):
     
    # looping till length l
   # for i in range(0, len(l), n):
       # yield l[i:i + n]

In [19]:
train_chunks = divide_chunks(list(Train[0]), 1500)
test_chunks = divide_chunks(list(Test[0]), 1500)

In [18]:
len(list(train_chunks))

10

In [10]:
td.create_chunks(df_raw,Train, name="Train")

0 of 1500
100 of 1500
200 of 1500
300 of 1500
400 of 1500
500 of 1500
600 of 1500
700 of 1500
800 of 1500
900 of 1500
1000 of 1500
1100 of 1500
1200 of 1500
1300 of 1500
1400 of 1500
0 of 1500
100 of 1500
200 of 1500
300 of 1500
400 of 1500
500 of 1500
600 of 1500
700 of 1500
800 of 1500
900 of 1500
1000 of 1500
1100 of 1500
1200 of 1500
1300 of 1500
1400 of 1500
0 of 1500
100 of 1500
200 of 1500
300 of 1500
400 of 1500
500 of 1500
600 of 1500
700 of 1500
800 of 1500
900 of 1500
1000 of 1500
1100 of 1500
1200 of 1500
1300 of 1500
1400 of 1500
0 of 1500
100 of 1500
200 of 1500
300 of 1500
400 of 1500
500 of 1500
600 of 1500
700 of 1500
800 of 1500
900 of 1500
1000 of 1500
1100 of 1500
1200 of 1500
1300 of 1500
1400 of 1500
0 of 1500
100 of 1500
200 of 1500
300 of 1500
400 of 1500
500 of 1500
600 of 1500
700 of 1500
800 of 1500
900 of 1500
1000 of 1500
1100 of 1500
1200 of 1500
1300 of 1500
1400 of 1500
0 of 1500
100 of 1500
200 of 1500
300 of 1500
400 of 1500
500 of 1500
600 of 1500
700 of 1500
800 of 1500
900 of 1500
1000 of 1500
1100 of 1500
1200 of 1500
1300 of 1500
1400 of 1500
0 of 1500
100 of 1500
200 of 1500
300 of 1500
400 of 1500
500 of 1500
600 of 1500
700 of 1500
800 of 1500
900 of 1500
1000 of 1500
1100 of 1500
1200 of 1500
1300 of 1500
1400 of 1500
0 of 1500
100 of 1500
200 of 1500
300 of 1500
400 of 1500
500 of 1500
600 of 1500
700 of 1500
800 of 1500
900 of 1500
1000 of 1500
1100 of 1500
1200 of 1500
1300 of 1500
1400 of 1500
0 of 1500
100 of 1500
200 of 1500
300 of 1500
400 of 1500
500 of 1500
600 of 1500
700 of 1500
800 of 1500
900 of 1500
1000 of 1500
1100 of 1500
1200 of 1500
1300 of 1500
1400 of 1500
0 of 702
100 of 702
200 of 702
300 of 702
400 of 702
500 of 702
600 of 702

In [11]:
df_old = pd.DataFrame()
for i in range(1,11):
    df_new = pd.read_parquet(f"data/datachunks/chunk{i}.parquet")
    df_old = pd.concat([df_old, df_new])

In [38]:
df_old.tail()

                      smart_1_raw  smart_3_raw  smart_4_raw  smart_5_raw  \
instances timepoints
378567    9           194017136.0          0.0         16.0          0.0
          10           63775384.0          0.0         16.0          0.0
          11           36359072.0          0.0         16.0          0.0
          12           49411568.0          0.0         16.0          0.0
          13          103651952.0          0.0         16.0          0.0

                      smart_7_raw  smart_9_raw  smart_10_raw  smart_12_raw  \
instances timepoints
378567    9           915103079.0      64409.0           0.0          16.0
          10          916456857.0      64433.0           0.0          16.0
          11          918523712.0      64457.0           0.0          16.0
          12          919579324.0      64481.0           0.0          16.0
          13          920864935.0      64505.0           0.0          16.0

                      smart_187_raw  smart_188_raw  ...  smart_188_normalized  \
instances timepoints                                ...
378567    9                     0.0            0.0  ...                 100.0
          10                    0.0            0.0  ...                 100.0
          11                    0.0            0.0  ...                 100.0
          12                    0.0            0.0  ...                 100.0
          13                    0.0            0.0  ...                 100.0

                      smart_192_normalized  smart_193_normalized  \
instances timepoints
378567    9                          100.0                  91.0
          10                         100.0                  91.0
          11                         100.0                  91.0
          12                         100.0                  91.0
          13                         100.0                  91.0

                      smart_194_normalized  smart_197_normalized  \
instances timepoints
378567    9                           22.0                 100.0
          10                          22.0                 100.0
          11                          22.0                 100.0
          12                          22.0                 100.0
          13                          23.0                 100.0

                      smart_198_normalized smart_199_normalized faildate  \
instances timepoints
378567    9                          100.0                200.0      NaT
          10                         100.0                200.0      NaT
          11                         100.0                200.0      NaT
          12                         100.0                200.0      NaT
          13                         100.0                200.0      NaT

                     Time_till_failure  failing_in14days
instances timepoints
378567    9                        NaT               0.0
          10                       NaT               0.0
          11                       NaT               0.0
          12                       NaT               0.0
          13                       NaT               0.0

[5 rows x 40 columns]

In [13]:
df_old.head(20)

                      smart_1_raw  smart_3_raw  smart_4_raw  smart_5_raw  \
instances timepoints
0         0            57293128.0          0.0         10.0          0.0
          1           222793344.0          0.0         10.0          0.0
          2            73042800.0          0.0         10.0          0.0
          3           207837040.0          0.0         10.0          0.0
          4            12126328.0          0.0         10.0          0.0
          5            54552168.0          0.0         10.0          0.0
          6           234211992.0          0.0         10.0          0.0
          7           144623440.0          0.0         10.0          0.0
          8            12438160.0          0.0         10.0          0.0
          9           234663208.0          0.0         10.0          0.0
          10           32052592.0          0.0         10.0          0.0
          11          183512528.0          0.0         10.0          0.0
          12          136358944.0          0.0         10.0          0.0
          13          204052864.0          0.0         10.0          0.0
1         0           123824400.0          0.0         10.0          0.0
          1            89835104.0          0.0         10.0          0.0
          2            62047048.0          0.0         10.0          0.0
          3            13106008.0          0.0         10.0          0.0
          4            11478424.0          0.0         10.0          0.0
          5           171976656.0          0.0         10.0          0.0

                      smart_7_raw  smart_9_raw  smart_10_raw  smart_12_raw  \
instances timepoints
0         0           353905178.0      58103.0           0.0          10.0
          1           355108650.0      58126.0           0.0          10.0
          2           357104171.0      58150.0           0.0          10.0
          3           359671059.0      58174.0           0.0          10.0
          4           361958335.0      58198.0           0.0          10.0
          5           363003394.0      58221.0           0.0          10.0
          6           366413500.0      58257.0           0.0          10.0
          7           367799328.0      58281.0           0.0          10.0
          8           369433157.0      58304.0           0.0          10.0
          9           370769849.0      58328.0           0.0          10.0
          10          372113073.0      58352.0           0.0          10.0
          11          373600480.0      58364.0           0.0          10.0
          12          376178846.0      58387.0           0.0          10.0
          13          379223258.0      58411.0           0.0          10.0
1         0           380884729.0      58435.0           0.0          10.0
          1           382750401.0      58458.0           0.0          10.0
          2           384293724.0      58482.0           0.0          10.0
          3           385519766.0      58506.0           0.0          10.0
          4           387966567.0      58541.0           0.0          10.0
          5           389758192.0      58565.0           0.0          10.0

                      smart_187_raw  smart_188_raw  ...  smart_188_normalized  \
instances timepoints                                ...
0         0                     0.0            0.0  ...                 100.0
          1                     0.0            0.0  ...                 100.0
          2                     0.0            0.0  ...                 100.0
          3                     0.0            0.0  ...                 100.0
          4                     0.0            0.0  ...                 100.0
          5                     0.0            0.0  ...                 100.0
          6                     0.0            0.0  ...                 100.0
          7                     0.0            0.0  ...                 100.0
          8                     0.0            0.0  ...                 100.0
          9                     0.0            0.0  ...                 100.0
          10                    0.0            0.0  ...                 100.0
          11                    0.0            0.0  ...                 100.0
          12                    0.0            0.0  ...                 100.0
          13                    0.0            0.0  ...                 100.0
1         0                     0.0            0.0  ...                 100.0
          1                     0.0            0.0  ...                 100.0
          2                     0.0            0.0  ...                 100.0
          3                     0.0            0.0  ...                 100.0
          4                     0.0            0.0  ...                 100.0
          5                     0.0            0.0  ...                 100.0

                      smart_192_normalized  smart_193_normalized  \
instances timepoints
0         0                          100.0                  80.0
          1                          100.0                  80.0
          2                          100.0                  80.0
          3                          100.0                  80.0
          4                          100.0                  80.0
          5                          100.0                  80.0
          6                          100.0                  80.0
          7                          100.0                  80.0
          8                          100.0                  80.0
          9                          100.0                  80.0
          10                         100.0                  80.0
          11                         100.0                  80.0
          12                         100.0                  80.0
          13                         100.0                  80.0
1         0                          100.0                  80.0
          1                          100.0                  80.0
          2                          100.0                  80.0
          3                          100.0                  80.0
          4                          100.0                  80.0
          5                          100.0                  80.0

                      smart_194_normalized  smart_197_normalized  \
instances timepoints
0         0                           22.0                 100.0
          1                           22.0                 100.0
          2                           22.0                 100.0
          3                           22.0                 100.0
          4                           21.0                 100.0
          5                           22.0                 100.0
          6                           21.0                 100.0
          7                           21.0                 100.0
          8                           21.0                 100.0
          9                           21.0                 100.0
          10                          22.0                 100.0
          11                          22.0                 100.0
          12                          22.0                 100.0
          13                          22.0                 100.0
1         0                           22.0                 100.0
          1                           21.0                 100.0
          2                           21.0                 100.0
          3                           22.0                 100.0
          4                           22.0                 100.0
          5                           22.0                 100.0

                      smart_198_normalized smart_199_normalized faildate  \
instances timepoints
0         0                          100.0                200.0      NaT
          1                          100.0                200.0      NaT
          2                          100.0                200.0      NaT
          3                          100.0                200.0      NaT
          4                          100.0                200.0      NaT
          5                          100.0                200.0      NaT
          6                          100.0                200.0      NaT
          7                          100.0                200.0      NaT
          8                          100.0                200.0      NaT
          9                          100.0                200.0      NaT
          10                         100.0                200.0      NaT
          11                         100.0                200.0      NaT
          12                         100.0                200.0      NaT
          13                         100.0                200.0      NaT
1         0                          100.0                200.0      NaT
          1                          100.0                200.0      NaT
          2                          100.0                200.0      NaT
          3                          100.0                200.0      NaT
          4                          100.0                200.0      NaT
          5                          100.0                200.0      NaT

                     Time_till_failure  failing_in14days
instances timepoints
0         0                        NaT               0.0
          1                        NaT               0.0
          2                        NaT               0.0
          3                        NaT               0.0
          4                        NaT               0.0
          5                        NaT               0.0
          6                        NaT               0.0
          7                        NaT               0.0
          8                        NaT               0.0
          9                        NaT               0.0
          10                       NaT               0.0
          11                       NaT               0.0
          12                       NaT               0.0
          13                       NaT               0.0
1         0                        NaT               0.0
          1                        NaT               0.0
          2                        NaT               0.0
          3                        NaT               0.0
          4                        NaT               0.0
          5                        NaT               0.0

[20 rows x 40 columns]

In [27]:
# code courtesy of jezrael on stackoverflow (https://stackoverflow.com/questions/46445965/reset-a-recurring-multiindex-in-pandas)
a1 = df_old.index.get_level_values(0).to_series()
a2 = a1.ne(a1.shift()).cumsum() - 1

mux = pd.MultiIndex.from_arrays([a2, df_old.index.get_level_values(1)], names=df_old.index.names)

df_old.index = mux

In [28]:
y_train = td.create_y(df_old)

In [35]:
len(y_train)

378568

In [39]:
y_train = X_train.iloc[::14, :]["failing_in14days"].astype(int).reset_index(drop=True)

NameError: name 'X_train' is not defined

In [62]:
#y = []
#for instance in df_old.index.levels[0]:
    #if 1.0 in list(df_old.loc[(instance),"failing_in14days"]):
       # y.append(1)
    #else: 
        #y.append(0)

In [29]:
df_old.loc[(0),"failing_in14days"]

timepoints
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
Name: failing_in14days, dtype: float64

In [30]:
df_old

                      smart_1_raw  smart_3_raw  smart_4_raw  smart_5_raw  \
instances timepoints
0         0            57293128.0          0.0         10.0          0.0
          1           222793344.0          0.0         10.0          0.0
          2            73042800.0          0.0         10.0          0.0
          3           207837040.0          0.0         10.0          0.0
          4            12126328.0          0.0         10.0          0.0
...                           ...          ...          ...          ...
378567    9           194017136.0          0.0         16.0          0.0
          10           63775384.0          0.0         16.0          0.0
          11           36359072.0          0.0         16.0          0.0
          12           49411568.0          0.0         16.0          0.0
          13          103651952.0          0.0         16.0          0.0

                      smart_7_raw  smart_9_raw  smart_10_raw  smart_12_raw  \
instances timepoints
0         0           353905178.0      58103.0           0.0          10.0
          1           355108650.0      58126.0           0.0          10.0
          2           357104171.0      58150.0           0.0          10.0
          3           359671059.0      58174.0           0.0          10.0
          4           361958335.0      58198.0           0.0          10.0
...                           ...          ...           ...           ...
378567    9           915103079.0      64409.0           0.0          16.0
          10          916456857.0      64433.0           0.0          16.0
          11          918523712.0      64457.0           0.0          16.0
          12          919579324.0      64481.0           0.0          16.0
          13          920864935.0      64505.0           0.0          16.0

                      smart_187_raw  smart_188_raw  ...  smart_188_normalized  \
instances timepoints                                ...
0         0                     0.0            0.0  ...                 100.0
          1                     0.0            0.0  ...                 100.0
          2                     0.0            0.0  ...                 100.0
          3                     0.0            0.0  ...                 100.0
          4                     0.0            0.0  ...                 100.0
...                             ...            ...  ...                   ...
378567    9                     0.0            0.0  ...                 100.0
          10                    0.0            0.0  ...                 100.0
          11                    0.0            0.0  ...                 100.0
          12                    0.0            0.0  ...                 100.0
          13                    0.0            0.0  ...                 100.0

                      smart_192_normalized  smart_193_normalized  \
instances timepoints
0         0                          100.0                  80.0
          1                          100.0                  80.0
          2                          100.0                  80.0
          3                          100.0                  80.0
          4                          100.0                  80.0
...                                    ...                   ...
378567    9                          100.0                  91.0
          10                         100.0                  91.0
          11                         100.0                  91.0
          12                         100.0                  91.0
          13                         100.0                  91.0

                      smart_194_normalized  smart_197_normalized  \
instances timepoints
0         0                           22.0                 100.0
          1                           22.0                 100.0
          2                           22.0                 100.0
          3                           22.0                 100.0
          4                           21.0                 100.0
...                                    ...                   ...
378567    9                           22.0                 100.0
          10                          22.0                 100.0
          11                          22.0                 100.0
          12                          22.0                 100.0
          13                          23.0                 100.0

                      smart_198_normalized smart_199_normalized faildate  \
instances timepoints
0         0                          100.0                200.0      NaT
          1                          100.0                200.0      NaT
          2                          100.0                200.0      NaT
          3                          100.0                200.0      NaT
          4                          100.0                200.0      NaT
...                                    ...                  ...      ...
378567    9                          100.0                200.0      NaT
          10                         100.0                200.0      NaT
          11                         100.0                200.0      NaT
          12                         100.0                200.0      NaT
          13                         100.0                200.0      NaT

                     Time_till_failure  failing_in14days
instances timepoints
0         0                        NaT               0.0
          1                        NaT               0.0
          2                        NaT               0.0
          3                        NaT               0.0
          4                        NaT               0.0
...                                ...               ...
378567    9                        NaT               0.0
          10                       NaT               0.0
          11                       NaT               0.0
          12                       NaT               0.0
          13                       NaT               0.0

[5299952 rows x 40 columns]

In [31]:
from sktime.transformations.panel.rocket import Rocket
from sktime.datatypes import convert,convert_to,mtype,check_raise

In [40]:
rocket = Rocket()

In [41]:
col_list = td.feature_list(target=False)
df_rocket = df_old[col_list]

In [42]:
X_train2 = convert(df_rocket,from_type="pd-multiindex", to_type="df-list")

In [ ]:
rocket.fit(df_old)

In [ ]:
transform_x= rocket.transform(df_old)

In [ ]:
transformed_x[1].min()

In [ ]:
y_train

In [ ]:
classifier=RidgeclassifierCV(alpas=np.logspace(-3,3,10))
classifier.fit(transform_x,y_train)

In [ ]:
type(X_train2[0])

In [43]:
rocket.fit(X_train2)

Rocket()

In [44]:
transformed_X = rocket.transform(X_train2)

:

:

In [ ]:
transformed_X